# SPDX-FileCopyrightText: 2024 Birger Schacht <birger.schacht@oeaw.ac.at>
# SPDX-License-Identifier: MIT
name: Run linters

on:
  - push

jobs:
  ruff-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run ruff format
        run: uv run --only-dev ruff format --check .

  ruff-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run ruff check
        run: uv run --only-dev ruff check .

  djlint-formatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run djLint formatter
        run: uv run --only-dev djlint --check  .

  djlint-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run djLint linter
        run: uv run --only-dev djlint --lint .

  deptry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run deptry
        run: uv run --only-dev deptry .
